server:
  port: 9292
  max-http-header-size: 18432
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@10.0.130.27:1521:orcl
    url: jdbc:oracle:thin:@10.0.119.2:1521:orcl
    username: biuser
    password: GMfr2020

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://106.14.210.23:5306/sharing_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: ant456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idel: 0
    timeout: 10000
#mybatis:
#  # spring boot集成mybatis的方式打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl